[tool.poetry]
name = "wren-ai-service"
version = "0.27.15"
description = ""
authors = ["dev@getwren.ai"]
license = "AGPL-3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12.*, <3.13"
fastapi = "^0.120.1"
uvicorn = {extras = ["standard"], version = "^0.38.0"} # Litellm requires uvicorn < 0.30.0
python-dotenv = "^1.2.1"
haystack-ai = "==2.19.0"
openai = "^2.6.1"
qdrant-haystack = "^9.1.2"
backoff = "^2.2.1"
tqdm = "^4.66.4"
numpy = "^2.3.4"
sqlparse = "^0.5.0"
orjson = "^3.11.4"
sf-hamilton = {version = "^1.69.0"}
aiohttp = {extras = ["speedups"], version = "^3.10.2"}
ollama-haystack = "^1.1.0"
langfuse = "^2.43.3"
ollama = "^0.6.0"
toml = "^0.10.2"
sqlglot = {extras = ["rs"], version = "^27.28.1"}
cachetools = "^6.2.1"
pyyaml = "^6.0.2"
pydantic-settings = "^2.5.2"
google-auth = "^2.35.0"
tiktoken = "^0.12.0"
jsonschema = "^4.23.0"
litellm = "^1.79.0"
boto3 = "^1.40.60" # Litellm requires boto3 = 1.34.34
qdrant-client = "==1.15.1"
langchain-core = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.3.0"
streamlit = "^1.37.0"
watchdog = "^6.0.0"
pandas = "^2.2.2"
matplotlib = "^3.9.2"
sseclient-py = "^1.8.0"
dspy-ai = "^3.0.3"
requests = "^2.32.4"
extra-streamlit-components = "^0.1.71"
deepeval = "^3.6.9"
tomlkit = "^0.13.0"
nltk = "^3.9.1"
psycopg2 = "^2.9.10"
langchain = "^1.0.2"

[tool.poetry.group.eval.dependencies]
gitpython = "^3.1.43"
plotly = "^6.3.1"
nbformat = "^5.1.3"
ipykernel = "^7.1.0"
itables = "^2.2.1"
gdown = "^5.2.0"
streamlit-tags = "^1.2.8"
docker = "^7.1.0"

[tool.poetry.group.test.dependencies]
locust = "^2.42.1"
pytest = "^8.3.0"
pytest-cov = "^7.0.0"
pytest-asyncio = "^1.2.0"
aioresponses = "^0.7.0"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
